### ISSUE TITLE
config.yaml file

### ISSUE THREAD

**Issue by lysanderism** [wsntxxn/TextToAudioGrounding#1]
hello, can you provide the config.yaml file? without this i can't run the code

**Comment by wsntxxn** [comment]
I have updated the codes and the baseline configuration files. Please check.

**Comment by lysanderism** [comment]
thanks a lot. I'm from Tongji university, appreciate for your work

**Comment by lysanderism** [comment]
author, It seems like you forget to upload the pack_waveform.py file in data ?

**Comment by wsntxxn** [comment]
Sorry for the missing, uploaded.

**Comment by lysanderism** [comment]
in eval_util.py function "compute_intersection_based_threshold_auc" are missed, in run.py there is a function "compute_intersection_based_threshold_auc".

**Comment by wsntxxn** [comment]
This function is no longer used now. Only the `evaluate` function in run.py is used.
